# Generated by Django 5.2 on 2026-04-01 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_telegramchannel"),
    ]

    operations = [
        migrations.CreateModel(
            name="Advertisement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Internal label — not shown to readers.",
                        max_length=100,
                    ),
                ),
                (
                    "placement",
                    models.CharField(
                        choices=[
                            ("homepage_banner", "Homepage — Top Banner (728×90)"),
                            ("homepage_sidebar", "Homepage — Sidebar (300×250)"),
                            ("article_top", "Article — After Image (responsive)"),
                            (
                                "article_bottom",
                                "Article — Above Related Stories (728×90)",
                            ),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "ad_code",
                    models.TextField(
                        help_text="Paste your Google AdSense &lt;ins&gt; block or any HTML ad code here."
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={"ordering": ["placement", "-updated_at"],},
        ),
    ]
