# Generated by Django 5.2 on 2026-04-03 10:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_advertisement"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="advertisement",
            name="client_name",
            field=models.CharField(
                blank=True,
                help_text="Name of the advertiser (e.g. 'Habesha Brewery'). Only visible to admins.",
                max_length=150,
            ),
        ),
        migrations.AddField(
            model_name="advertisement",
            name="image_url",
            field=models.URLField(
                blank=True,
                help_text="URL of the ad image (JPG/PNG/GIF/WebP). Use this for personal-connection ads.",
            ),
        ),
        migrations.AddField(
            model_name="advertisement",
            name="link_url",
            field=models.URLField(
                blank=True, help_text="Where the ad links to when clicked."
            ),
        ),
        migrations.AlterField(
            model_name="advertisement",
            name="ad_code",
            field=models.TextField(
                blank=True,
                help_text="Paste a Google AdSense &lt;ins&gt; block, or any custom HTML. Leave blank if using the image fields above.",
            ),
        ),
        migrations.CreateModel(
            name="PageView",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("path", models.CharField(db_index=True, max_length=500)),
                (
                    "session_key",
                    models.CharField(blank=True, db_index=True, max_length=100),
                ),
                ("date", models.DateField(auto_now_add=True, db_index=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="page_views",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["date", "path"], name="core_pagevi_date_d1ee4d_idx"
                    )
                ],
            },
        ),
    ]
